"""add_updated_at_to_partidas

Revision ID: 6d33b6b3539d
Revises: d12cab13d5e1
Create Date: 2026-01-31 23:20:59.179381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d33b6b3539d'
down_revision = 'd12cab13d5e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partidas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partidas', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
