"""add_detailed_stats_cols

Revision ID: 984d252a71a6
Revises: 6d33b6b3539d
Create Date: 2026-01-31 23:23:48.370221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '984d252a71a6'
down_revision = '6d33b6b3539d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estatisticas_partidas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chutes_gol_casa', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('chutes_gol_fora', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('chutes_bloqueados_casa', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('chutes_bloqueados_fora', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estatisticas_partidas', schema=None) as batch_op:
        batch_op.drop_column('chutes_bloqueados_fora')
        batch_op.drop_column('chutes_bloqueados_casa')
        batch_op.drop_column('chutes_gol_fora')
        batch_op.drop_column('chutes_gol_casa')

    # ### end Alembic commands ###
