"""add_halftime_scores

Revision ID: 9d06f513e479
Revises: d6ec278b8be0
Create Date: 2026-01-31 23:00:49.432721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d06f513e479'
down_revision = 'd6ec278b8be0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partidas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gols_casa_intervalo', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('gols_fora_intervalo', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partidas', schema=None) as batch_op:
        batch_op.drop_column('gols_fora_intervalo')
        batch_op.drop_column('gols_casa_intervalo')

    # ### end Alembic commands ###
