"""add_event_escalation_schema

Revision ID: b46b38acced1
Revises: c55a40be6fa8
Create Date: 2026-01-31 23:31:04.391604

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b46b38acced1'
down_revision = 'c55a40be6fa8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('escalacoes',
    sa.Column('partida_id', sa.Integer(), nullable=False),
    sa.Column('jogador_id', sa.Integer(), nullable=False),
    sa.Column('time_id', sa.Integer(), nullable=False),
    sa.Column('titular', sa.Boolean(), nullable=True),
    sa.Column('numero_camisa', sa.String(length=10), nullable=True),
    sa.Column('nota', sa.Float(), nullable=True),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['jogador_id'], ['jogadores.id'], ),
    sa.ForeignKeyConstraint(['partida_id'], ['partidas.id'], ),
    sa.ForeignKeyConstraint(['time_id'], ['times.id'], ),
    sa.PrimaryKeyConstraint('partida_id', 'jogador_id')
    )
    with op.batch_alter_table('eventos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('minuto_adicional', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('jogador_secundario_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'jogadores', ['jogador_secundario_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eventos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('jogador_secundario_id')
        batch_op.drop_column('minuto_adicional')

    op.drop_table('escalacoes')
    # ### end Alembic commands ###
