"""add_escanteios_cols

Revision ID: c55a40be6fa8
Revises: 984d252a71a6
Create Date: 2026-01-31 23:27:18.088959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c55a40be6fa8'
down_revision = '984d252a71a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estatisticas_partidas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('escanteios_casa', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('escanteios_fora', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estatisticas_partidas', schema=None) as batch_op:
        batch_op.drop_column('escanteios_fora')
        batch_op.drop_column('escanteios_casa')

    # ### end Alembic commands ###
