"""add_strict_context_cols

Revision ID: d12cab13d5e1
Revises: 9d06f513e479
Create Date: 2026-01-31 23:09:00.025102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd12cab13d5e1'
down_revision = '9d06f513e479'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partidas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('liga_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ano', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'ligas', ['liga_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partidas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('ano')
        batch_op.drop_column('liga_id')
        batch_op.drop_column('start_time')

    # ### end Alembic commands ###
