"""Refactor v1: Standardize PT and Optimize

Revision ID: d6ec278b8be0
Revises: 
Create Date: 2026-01-31 22:33:47.704995

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd6ec278b8be0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('arbitros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('estado', sa.String(length=2), nullable=True),
    sa.Column('categoria', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('estadios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=2), nullable=True),
    sa.Column('capacidade', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('ligas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('pais', sa.String(length=100), nullable=False),
    sa.Column('confederacao', sa.String(length=20), nullable=True),
    sa.Column('num_times', sa.Integer(), nullable=True),
    sa.Column('num_rodadas', sa.Integer(), nullable=True),
    sa.Column('ogol_slug', sa.String(length=100), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('temporadas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('liga_id', sa.Integer(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=True),
    sa.Column('data_fim', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.Column('ogol_edition_id', sa.String(length=50), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['liga_id'], ['ligas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('temporadas', schema=None) as batch_op:
        batch_op.create_index('idx_temporadas_current', ['liga_id'], unique=False, postgresql_where=sa.text('is_current = true'))

    op.create_table('times',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('escudo_url', sa.Text(), nullable=True),
    sa.Column('liga_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['liga_id'], ['ligas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('jogadores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('time_atual_id', sa.Integer(), nullable=True),
    sa.Column('posicao', sa.String(length=50), nullable=True),
    sa.Column('nacionalidade', sa.String(length=50), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('id_fonte', sa.String(length=100), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['time_atual_id'], ['times.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('partidas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('temporada_id', sa.Integer(), nullable=False),
    sa.Column('rodada', sa.Integer(), nullable=False),
    sa.Column('time_casa_id', sa.Integer(), nullable=False),
    sa.Column('time_fora_id', sa.Integer(), nullable=False),
    sa.Column('gols_casa', sa.Integer(), nullable=True),
    sa.Column('gols_fora', sa.Integer(), nullable=True),
    sa.Column('data_hora', sa.DateTime(), nullable=True),
    sa.Column('estadio_id', sa.Integer(), nullable=True),
    sa.Column('arbitro_id', sa.Integer(), nullable=True),
    sa.Column('publico', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('url_fonte', sa.String(length=255), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['arbitro_id'], ['arbitros.id'], ),
    sa.ForeignKeyConstraint(['estadio_id'], ['estadios.id'], ),
    sa.ForeignKeyConstraint(['temporada_id'], ['temporadas.id'], ),
    sa.ForeignKeyConstraint(['time_casa_id'], ['times.id'], ),
    sa.ForeignKeyConstraint(['time_fora_id'], ['times.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('temporada_id', 'rodada', 'time_casa_id', 'time_fora_id', name='partida_unica'),
    sa.UniqueConstraint('url_fonte')
    )
    with op.batch_alter_table('partidas', schema=None) as batch_op:
        batch_op.create_index('idx_partidas_dashboard', ['temporada_id', 'status', 'data_hora'], unique=False, postgresql_include=['id', 'time_casa_id', 'time_fora_id', 'gols_casa', 'gols_fora'])
        batch_op.create_index('idx_partidas_time_casa_history', ['time_casa_id', 'data_hora'], unique=False)
        batch_op.create_index('idx_partidas_time_fora_history', ['time_fora_id', 'data_hora'], unique=False)

    op.create_table('times_temporadas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time_id', sa.Integer(), nullable=False),
    sa.Column('temporada_id', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('posicao', sa.Integer(), nullable=True),
    sa.Column('pontos', sa.Integer(), nullable=True),
    sa.Column('vitorias', sa.Integer(), nullable=True),
    sa.Column('empates', sa.Integer(), nullable=True),
    sa.Column('derrotas', sa.Integer(), nullable=True),
    sa.Column('gols_pro', sa.Integer(), nullable=True),
    sa.Column('gols_contra', sa.Integer(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['temporada_id'], ['temporadas.id'], ),
    sa.ForeignKeyConstraint(['time_id'], ['times.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('time_id', 'temporada_id', name='time_temporada_unica')
    )
    with op.batch_alter_table('times_temporadas', schema=None) as batch_op:
        batch_op.create_index('idx_times_temporadas_posicao', ['temporada_id', 'posicao'], unique=False)

    op.create_table('estatisticas_partidas',
    sa.Column('partida_id', sa.Integer(), nullable=False),
    sa.Column('posse_casa', sa.Integer(), nullable=True),
    sa.Column('posse_fora', sa.Integer(), nullable=True),
    sa.Column('chutes_casa', sa.Integer(), nullable=True),
    sa.Column('chutes_fora', sa.Integer(), nullable=True),
    sa.Column('xg_casa', sa.Float(), nullable=True),
    sa.Column('xg_fora', sa.Float(), nullable=True),
    sa.Column('xgot_casa', sa.Float(), nullable=True),
    sa.Column('xgot_fora', sa.Float(), nullable=True),
    sa.Column('passes_casa', sa.Integer(), nullable=True),
    sa.Column('passes_fora', sa.Integer(), nullable=True),
    sa.Column('passes_certos_casa', sa.Integer(), nullable=True),
    sa.Column('passes_certos_fora', sa.Integer(), nullable=True),
    sa.Column('passes_precisao_casa', sa.Float(), nullable=True),
    sa.Column('passes_precisao_fora', sa.Float(), nullable=True),
    sa.Column('faltas_casa', sa.Integer(), nullable=True),
    sa.Column('faltas_fora', sa.Integer(), nullable=True),
    sa.Column('impedimentos_casa', sa.Integer(), nullable=True),
    sa.Column('impedimentos_fora', sa.Integer(), nullable=True),
    sa.Column('defesas_goleiro_casa', sa.Integer(), nullable=True),
    sa.Column('defesas_goleiro_fora', sa.Integer(), nullable=True),
    sa.Column('cortes_casa', sa.Integer(), nullable=True),
    sa.Column('cortes_fora', sa.Integer(), nullable=True),
    sa.Column('interceptacoes_casa', sa.Integer(), nullable=True),
    sa.Column('interceptacoes_fora', sa.Integer(), nullable=True),
    sa.Column('amarelos_casa', sa.Integer(), nullable=True),
    sa.Column('amarelos_fora', sa.Integer(), nullable=True),
    sa.Column('vermelhos_casa', sa.Integer(), nullable=True),
    sa.Column('vermelhos_fora', sa.Integer(), nullable=True),
    sa.Column('duelos_ganhos_casa', sa.Integer(), nullable=True),
    sa.Column('duelos_ganhos_fora', sa.Integer(), nullable=True),
    sa.Column('duelos_aereos_ganhos_casa', sa.Integer(), nullable=True),
    sa.Column('duelos_aereos_ganhos_fora', sa.Integer(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['partida_id'], ['partidas.id'], ),
    sa.PrimaryKeyConstraint('partida_id')
    )
    with op.batch_alter_table('estatisticas_partidas', schema=None) as batch_op:
        batch_op.create_index('idx_estatisticas_xg', ['xg_casa', 'xg_fora'], unique=False)

    op.create_table('eventos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('partida_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('minuto', sa.Integer(), nullable=True),
    sa.Column('periodo', sa.Integer(), nullable=True),
    sa.Column('time_id', sa.Integer(), nullable=True),
    sa.Column('jogador_id', sa.Integer(), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['jogador_id'], ['jogadores.id'], ),
    sa.ForeignKeyConstraint(['partida_id'], ['partidas.id'], ),
    sa.ForeignKeyConstraint(['time_id'], ['times.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('eventos', schema=None) as batch_op:
        batch_op.create_index('idx_eventos_timeline', ['partida_id', 'periodo', 'minuto'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eventos', schema=None) as batch_op:
        batch_op.drop_index('idx_eventos_timeline')

    op.drop_table('eventos')
    with op.batch_alter_table('estatisticas_partidas', schema=None) as batch_op:
        batch_op.drop_index('idx_estatisticas_xg')

    op.drop_table('estatisticas_partidas')
    with op.batch_alter_table('times_temporadas', schema=None) as batch_op:
        batch_op.drop_index('idx_times_temporadas_posicao')

    op.drop_table('times_temporadas')
    with op.batch_alter_table('partidas', schema=None) as batch_op:
        batch_op.drop_index('idx_partidas_time_fora_history')
        batch_op.drop_index('idx_partidas_time_casa_history')
        batch_op.drop_index('idx_partidas_dashboard', postgresql_include=['id', 'time_casa_id', 'time_fora_id', 'gols_casa', 'gols_fora'])

    op.drop_table('partidas')
    op.drop_table('jogadores')
    op.drop_table('times')
    with op.batch_alter_table('temporadas', schema=None) as batch_op:
        batch_op.drop_index('idx_temporadas_current', postgresql_where=sa.text('is_current = true'))

    op.drop_table('temporadas')
    op.drop_table('ligas')
    op.drop_table('estadios')
    op.drop_table('arbitros')
    # ### end Alembic commands ###
